### ISSUE TITLE
Why not just make it fullscreen in the styles?

### ISSUE THREAD

**Issue by jakehm** [krvital/react-leaflet-fullscreen#1]
<Map 
          style={{height: "100vh", width: "100vw"}}
          zoom={this.state.zoom}
          center={position}
        >

**Comment by krvital** [comment]
Hi @jakehm  
Nice assumption, but
1. First of all this is Leaflet control element which changes the state of map fullscreen/not fullscreen
2. 100vh and 100vw not the same thing as fullscreen. Fullscreen mode means not only of 100% of viewport, but 100% of screen width and height.  Look here for more details [requestFullScreen](https://developer.mozilla.org/en-US/docs/Web/API/Element/requestFullScreen)
