### ISSUE TITLE
Add TypeScript support

### ISSUE THREAD

**Issue by cersimo97** [krvital/react-leaflet-fullscreen#17]

**Comment by krvital** [comment]
Ts support add in [v4.1.0](https://github.com/krvital/react-leaflet-fullscreen/commit/f81455b8334d70c7ad611675463a1b01ac1fd114). Let's check it!

[Here is the demo](https://codesandbox.io/s/react-leaflet-fullscreen-v4-ts-sxckcv?file=/src/App.tsx)
