### ISSUE TITLE
Not compatible with react-leaflet 4.0.0?

### ISSUE THREAD

**Issue by sfeu** [krvital/react-leaflet-fullscreen#18]
Got this error as soon as i add fullscreencontrols of react-leaflet-fullscreen 2.0.2 - anyone can confirm?

Uncaught Error: No context provided: useLeafletContext() can only be used in a descendant of <MapContainer>
    at useLeafletContext (context.js:9:1)
    at useLeafletControl (control.js:5:1)
    at LeafComponent (component.js:39:1)
    at renderWithHooks (react-dom.development.js:16175:1)
    at updateForwardRef (react-dom.development.js:20023:1)
    at beginWork (react-dom.development.js:22465:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4161:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4210:1)
    at invokeGuardedCallback (react-dom.development.js:4274:1)
    at beginWork$1 (react-dom.development.js:27405:1)

**Comment by jimenaCabrejas** [comment]
I'm having this error while trying to install the package
`npm ERR! Found: react-leaflet@4.0.0
npm ERR! node_modules/react-leaflet
npm ERR!   react-leaflet@"^4.0.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react-leaflet@"^3.x" from react-leaflet-fullscreen@2.0.2
npm ERR! node_modules/react-leaflet-fullscreen
npm ERR!   react-leaflet-fullscreen@"*" from the root project
npm ERR!`

**Comment by ffischer1984** [comment]
> Got this error as soon as i add fullscreencontrols of react-leaflet-fullscreen 2.0.2 - anyone can confirm?
> 
> Uncaught Error: No context provided: useLeafletContext() can only be used in a descendant of at useLeafletContext (context.js:9:1) at useLeafletControl (control.js:5:1) at LeafComponent (component.js:39:1) at renderWithHooks (react-dom.development.js:16175:1) at updateForwardRef (react-dom.development.js:20023:1) at beginWork (react-dom.development.js:22465:1) at HTMLUnknownElement.callCallback (react-dom.development.js:4161:1) at Object.invokeGuardedCallbackDev (react-dom.development.js:4210:1) at invokeGuardedCallback (react-dom.development.js:4274:1) at beginWork$1 (react-dom.development.js:27405:1)

Have the same problem

**Comment by amiryxe** [comment]
I have the same problem too

**Comment by tomerpaz** [comment]
This might help for someone - I had the same problem, so Instead of this tibrary I use:

import L from "leaflet";
import { createControlComponent } from '@react-leaflet/core';
import 'leaflet.fullscreen';

const FullscreenControl = createControlComponent(props => L.control.fullscreen(props))

export default FullscreenControl

**Comment by indofiz** [comment]
> 

How can i add icon, just miss fullscreen icon

**Comment by Brupes** [comment]
> > 
> 
> How can i add icon, just miss fullscreen icon

Not sure if you still need help, but all you need to do is to import the file `Control.FullScreen.css` from the package `leaflet.fullscreen` to your app using the following line `import 'leaflet.fullscreen/Control.FullScreen.css'`

You can also import it on the same file where you will add the code @tomerpaz posted (not recommended) ending with something like this:
```javascript
import L from "leaflet";
import { createControlComponent } from '@react-leaflet/core';
import 'leaflet.fullscreen';
import 'leaflet.fullscreen/Control.FullScreen.css'

const FullscreenControl = createControlComponent(props => L.control.fullscreen(props))

export default FullscreenControl
```

**Comment by CxrlosKenobi** [comment]
Any ideas on how to fix the duplicated render, therefore duplicated fullscreen icon on my leaflet map?

The code from @Brupes is indeed working but without removing the `<React.StrictMode>` the icon is duplicated with a non-event button above the original

**Comment by Brupes** [comment]
this is happening because the element is not removed when function `onRemoved` is called.
a temporary hotfix that can be done is replacing the code above with the one bellow so the removal of the element is done by us.
this is not the best thing to do since we do not have control on which fullscreen button we are removing, but since we wont have more than one button of this type on the map... why not?

```javascript
import L from 'leaflet';
import 'leaflet.fullscreen';
import 'leaflet.fullscreen/Control.FullScreen.css';
import { useEffect, useState } from 'react';
import { useMap } from 'react-leaflet';

const FullscreenControl = function (props: any) {
    const map = useMap();

    useEffect(() => {
        // create control
        const control = L.control.fullscreen(props);
        // link control to map
        control.addTo(map);

        return () => {
            // get leaflet-control-zoom-fullscreen elements that need to be removed from container
            const elementsToRemove =
                control.getContainer()?.getElementsByClassName('leaflet-control-zoom-fullscreen') ?? [];
            for (const element of elementsToRemove) {
                // remove them
                element.remove();
            }
        };
    }, []);

    return null;
};

export default FullscreenControl;
```

**Comment by molinto** [comment]
@Brupes Thanks for posting. I get a "_Property 'fullscreen' does not exist on type 'typeof control_' error when using this.

Issue with the line: L.control.fullscreen(props)

**Comment by Brupes** [comment]
do you have the same imports that i have?
the next 2 lines need to be like this

```javascript
import L from 'leaflet';
import 'leaflet.fullscreen';
```

**Comment by molinto** [comment]
Yep:

```"@types/leaflet": "^1.9.3",
"@types/leaflet-draw": "^1.0.6",
"@types/react": "^18.0.21",
"@types/react-dom": "^18.0.6",
"@types/react-leaflet": "^3.0.0",
"leaflet": "^1.9.3",
"leaflet-draw": "^1.0.4",
"leaflet.fullscreen": "^2.4.0",
"react": "^18.2.0",
"react-dom": "^18.2.0",
"react-leaflet": "^4.2.1",
"react-leaflet-draw": "^0.20.4"

![Screenshot](https://github.com/krvital/react-leaflet-fullscreen/assets/279285/6a86fff3-c146-4000-bbe8-349efc8efc97)

**Comment by guizmo** [comment]
> 

you are missing the types
this install will fix the issue
yarn add @types/leaflet.fullscreen -D

**Comment by barbalex** [comment]
All the npm libraries I tried had issues. I ended up building my own component, directly using `screenfull`:

```js
import React, { useCallback, useEffect, useState } from 'react'
import styled from '@emotion/styled'
import { FaExpandArrowsAlt, FaCompressArrowsAlt } from 'react-icons/fa'
import screenfull from 'screenfull'

const Button = styled.button`
  background-color: white;
  width: 34px;
  height: 34px;
  border-radius: 4px;
  border: 2px solid rgba(0, 0, 0, 0.2);
  background-clip: padding-box;
  cursor: pointer;
  text-align: center;
  padding: 0 4px;
  svg {
    color: rgba(0, 0, 0, 0.8) !important;
    height: 30px;
  }
  margin-top: 7px;
`

const FullscreenControl = ({ mapRef }) => {
  const [isFullscreen, setIsFullscreen] = useState(false)
  const onFullscreenChange = useCallback(
    () => setIsFullscreen(screenfull.isFullscreen),
    [],
  )
  useEffect(() => {
    screenfull.on('change', onFullscreenChange)
    return () => screenfull.off('change', onFullscreenChange)
  }, [onFullscreenChange])

  const onClick = useCallback(() => {
    if (screenfull.isEnabled) {
      screenfull.toggle(mapRef.current)
    }
  }, [mapRef])

  return (
    <Button
      onClick={onClick}
      title={isFullscreen ? 'Karte verkleinern' : 'Karte maximieren'}
    >
      {isFullscreen ? <FaCompressArrowsAlt /> : <FaExpandArrowsAlt />}
    </Button>
  )
}

export default FullscreenControl
```

`mapRef` is the ref of the div containing the map.

**Comment by krvital** [comment]
Hiyaa! 
I've finally got around to update it. We can use it now with react-leaflet v4
